### PR TITLE
Adding ability to get the device health as part of the device status object

### PR DESCRIPTION
**Pull request by north3221**
## Description:
<details of changes goes here>
Adding the device health endpoint to the api and then using that to allow refresh of device health. I've kept the refresh separate to the standard refresh, meaning you can have a different polling frequency. Especially thinking Home Assistant here, so other device refresh will be a webhook, but dont think you get device health via webhook?

This was HA can poll device health  

**Related issue (if applicable):** fixes #<pysmartthings issue number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Local tests pass with `tox`. **Your PR cannot be merged unless tests pass**
  - [x] There is no commented out code in this PR.
  - [ ] Tests have been added/updated and code coverage percentage does not drop. No exclusions in `.coveragerc` allowed
  - [ ] `README.MD` updated (if necessary)

### CODE REVIEW

**Comment by north3221** [comment]
Looks like needs some tests adding... Take a look at the PR and let me know what you think and I'll take a look at tests

**Comment by north3221** [comment]
hey @andrewsayre are you able to take a look at this PR please?

Feedback welcome, keen to get this into HA

**Comment by ranhorev** [comment]
@north3221 
did you give up on this?
I just noticed i can not see whether devices are connected or not :)

**Comment by north3221** [comment]
@ranhorev yeah it works on mine as I run it as a custom component. But I'm guessing @andrewsayre doesn't use/maintain this any more as never replied or accepted pr

**Comment by andrewsayre** [comment]
@north3221 Not sure why you sat that given this PR never passed the checks. Please rebase and address the issues and I'll be happy to review.

**Comment by north3221** [comment]
@andrewsayre cause you never replied to any of my comments to you?.. I am not 100% sure what I need to do on the tests (I'm not a dev) and I've killed off the git project I had for looking at this now

If you are open to the PR and could maybe provide some guidance I'll take another look?

**Comment by ranhorev** [comment]
@andrewsayre I will also be happy to help resolving this issue, but unfortunately I don't understand the problem. I see the only check that failed is coverage decreased. How can I find out the problem in order to address it?
Thanks

**Comment by ranhorev** [comment]
@north3221 I think perhaps the code is missing tests (in order to cover the added code)
Also, maybe it's a better idea to create DeviceHealth (similar to DeviceStatus) seeing that the device health is actually not part of the device status but a separate API call

**Comment by north3221** [comment]
@ranhorev yeah I knew it needed coverage, wasnt sure how tbh and when I got no reply to the initial pr and request to look, I figured it wasnt maintained so no point in me trying to figure it out. Also been migrating away from ss

Your proposal makes sense, I'll close this PR. Nice one

**Pull request closed without merging**
