### PR TITLE
device health api

### PR DESCRIPTION
**Pull request by ranhorev**
## Description:

Implement device health API request, returning information containing whether device is online\offline and last update time

**Related issue (if applicable):** fixes #49 

## Checklist:

- [X] The code change is tested and works locally.
- [X] Local tests pass.
- [X] There is no commented out code in this PR.
- [X] Tests have been added/updated and code coverage percentage does not drop. No exclusions in `.coveragerc` allowed
- [X] `README.MD` updated (if necessary)

### CODE REVIEW

**Comment by ranhorev** [comment]
@andrewsayre 
it seems the workflow is pending your approval, appreciate your attendance in order to push this feature
Thanks

**Comment by ranhorev** [comment]
@andrewsayre can you approve workflow again...

**Comment by andrewsayre** [comment]
Totally annoying... I need to figure out if that can be turned off.

**Comment by ranhorev** [comment]
@andrewsayre please do.. also every time i upload a fix i lose the previous checks and i can't double check myself.
anyway please approve again. sorry.

**Comment by ranhorev** [comment]
@andrewsayre is there anything else missing for the merge?

**Comment by ranhorev1** [comment]
@andrewsayre ?

**Comment by millallo** [comment]
any news about it?

**Pull request closed without merging**
