### PR TITLE
Support ac optional model (valided on my climate)

### PR DESCRIPTION
**Pull request by Teka101**
## Description:
Support ac optional mode (off, sleep, windFree, windFreeSleep) for climate.

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Local tests pass with `tox`. **Your PR cannot be merged unless tests pass**
  - [x] There is no commented out code in this PR.
  - [x] Tests have been added/updated and code coverage percentage does not drop. No exclusions in `.coveragerc` allowed
  - [ ] `README.MD` updated (if necessary)

### CODE REVIEW

**Comment by andrewsayre** [comment]
Custom capabilities can be changed by the engineer at any point and aren't suitable to make first-class attributes in this library.

**Comment by Teka101** [comment]
Sorry but i don't understand...

When i turn on my AC, i have to activate sleeping mode each time i want it... and i'm just trying to add this feature to Home Assistant

**Comment by marciogranzotto** [comment]
I agree with @Teka101
A lot of people have these air conditioners and want to use them on Home Assistant with all its features, so why not support them? @andrewsayre

**Comment by veista** [comment]
@marciogranzotto as promised here is 2 weeks of my life https://github.com/veista/smartthings. I completely understand @andrewsayre why these cannot be added to the official library/Integration. These custom.capabilities are not in ST standard, so they can change from device to device. This would be hard to support at this level.

**Comment by andrewsayre** [comment]
You can access any of the attributes via the `attributes` dictionary or invoke any command through the `command` method, regardless of capability. There doesn't need to be convenience properties and methods for this to work. HA references the capabilities list in the library to exclude subscriptions from things that don't provide value, but that behavior can easily be changed in HA to subscribe to custom capabilities if desired.

**Pull request closed without merging**
